/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SchoolId = IDL.Nat;
export const StaffId = IDL.Nat;
export const School = IDL.Record({
  'id' : SchoolId,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const StaffAccount = IDL.Record({
  'id' : StaffId,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'enabled' : IDL.Bool,
  'schoolId' : SchoolId,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'schoolId' : IDL.Opt(SchoolId),
});
export const ReportId = IDL.Nat;
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'submitted' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const Time = IDL.Int;
export const ReportCategory = IDL.Variant({
  'other' : IDL.Null,
  'suggestion' : IDL.Null,
  'mentalHealth' : IDL.Null,
  'bullying' : IDL.Null,
  'harassment' : IDL.Null,
});
export const Report = IDL.Record({
  'id' : ReportId,
  'status' : ReportStatus,
  'text' : IDL.Text,
  'schoolId' : SchoolId,
  'timestamp' : Time,
  'category' : ReportCategory,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSchool' : IDL.Func([IDL.Text, IDL.Text], [SchoolId], []),
  'createStaffAccount' : IDL.Func(
      [IDL.Principal, SchoolId, IDL.Text, IDL.Text],
      [StaffId],
      [],
    ),
  'deleteSchool' : IDL.Func([SchoolId], [], []),
  'deleteStaffAccount' : IDL.Func([StaffId], [], []),
  'getAdminDiagnostics' : IDL.Func(
      [],
      [
        IDL.Record({
          'userRole' : IDL.Text,
          'totalAdmins' : IDL.Nat,
          'hasAdminPermission' : IDL.Bool,
          'totalUsers' : IDL.Nat,
          'callerPrincipal' : IDL.Text,
          'isAdmin' : IDL.Bool,
          'hasUserPermission' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getAllSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
  'getAllSchoolsStats' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'totalReports' : IDL.Nat,
            'schoolId' : SchoolId,
            'schoolName' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAllStaff' : IDL.Func([], [IDL.Vec(StaffAccount)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyStaffAccount' : IDL.Func([], [IDL.Opt(StaffAccount)], ['query']),
  'getReportsBySchool' : IDL.Func([SchoolId], [IDL.Vec(Report)], ['query']),
  'getReportsBySchoolAndCategory' : IDL.Func(
      [SchoolId, ReportCategory],
      [IDL.Vec(Report)],
      ['query'],
    ),
  'getReportsBySchoolAndDateRange' : IDL.Func(
      [SchoolId, Time, Time],
      [IDL.Vec(Report)],
      ['query'],
    ),
  'getSchool' : IDL.Func([SchoolId], [IDL.Opt(School)], ['query']),
  'getSchoolStats' : IDL.Func(
      [SchoolId],
      [
        IDL.Record({
          'resolved' : IDL.Nat,
          'submitted' : IDL.Nat,
          'totalReports' : IDL.Nat,
          'reviewed' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getStaffBySchool' : IDL.Func([SchoolId], [IDL.Vec(StaffAccount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAnonymousReport' : IDL.Func(
      [SchoolId, ReportCategory, IDL.Text],
      [],
      [],
    ),
  'updateReportStatus' : IDL.Func([ReportId, ReportStatus], [], []),
  'updateSchool' : IDL.Func([SchoolId, IDL.Text, IDL.Text], [], []),
  'updateStaffAccount' : IDL.Func(
      [StaffId, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SchoolId = IDL.Nat;
  const StaffId = IDL.Nat;
  const School = IDL.Record({
    'id' : SchoolId,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const StaffAccount = IDL.Record({
    'id' : StaffId,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'enabled' : IDL.Bool,
    'schoolId' : SchoolId,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'schoolId' : IDL.Opt(SchoolId),
  });
  const ReportId = IDL.Nat;
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'submitted' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReportCategory = IDL.Variant({
    'other' : IDL.Null,
    'suggestion' : IDL.Null,
    'mentalHealth' : IDL.Null,
    'bullying' : IDL.Null,
    'harassment' : IDL.Null,
  });
  const Report = IDL.Record({
    'id' : ReportId,
    'status' : ReportStatus,
    'text' : IDL.Text,
    'schoolId' : SchoolId,
    'timestamp' : Time,
    'category' : ReportCategory,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSchool' : IDL.Func([IDL.Text, IDL.Text], [SchoolId], []),
    'createStaffAccount' : IDL.Func(
        [IDL.Principal, SchoolId, IDL.Text, IDL.Text],
        [StaffId],
        [],
      ),
    'deleteSchool' : IDL.Func([SchoolId], [], []),
    'deleteStaffAccount' : IDL.Func([StaffId], [], []),
    'getAdminDiagnostics' : IDL.Func(
        [],
        [
          IDL.Record({
            'userRole' : IDL.Text,
            'totalAdmins' : IDL.Nat,
            'hasAdminPermission' : IDL.Bool,
            'totalUsers' : IDL.Nat,
            'callerPrincipal' : IDL.Text,
            'isAdmin' : IDL.Bool,
            'hasUserPermission' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getAllSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
    'getAllSchoolsStats' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'totalReports' : IDL.Nat,
              'schoolId' : SchoolId,
              'schoolName' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAllStaff' : IDL.Func([], [IDL.Vec(StaffAccount)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyStaffAccount' : IDL.Func([], [IDL.Opt(StaffAccount)], ['query']),
    'getReportsBySchool' : IDL.Func([SchoolId], [IDL.Vec(Report)], ['query']),
    'getReportsBySchoolAndCategory' : IDL.Func(
        [SchoolId, ReportCategory],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'getReportsBySchoolAndDateRange' : IDL.Func(
        [SchoolId, Time, Time],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'getSchool' : IDL.Func([SchoolId], [IDL.Opt(School)], ['query']),
    'getSchoolStats' : IDL.Func(
        [SchoolId],
        [
          IDL.Record({
            'resolved' : IDL.Nat,
            'submitted' : IDL.Nat,
            'totalReports' : IDL.Nat,
            'reviewed' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getStaffBySchool' : IDL.Func(
        [SchoolId],
        [IDL.Vec(StaffAccount)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAnonymousReport' : IDL.Func(
        [SchoolId, ReportCategory, IDL.Text],
        [],
        [],
      ),
    'updateReportStatus' : IDL.Func([ReportId, ReportStatus], [], []),
    'updateSchool' : IDL.Func([SchoolId, IDL.Text, IDL.Text], [], []),
    'updateStaffAccount' : IDL.Func(
        [StaffId, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };