/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Report {
  'id' : ReportId,
  'status' : ReportStatus,
  'text' : string,
  'schoolId' : SchoolId,
  'timestamp' : Time,
  'category' : ReportCategory,
}
export type ReportCategory = { 'other' : null } |
  { 'suggestion' : null } |
  { 'mentalHealth' : null } |
  { 'bullying' : null } |
  { 'harassment' : null };
export type ReportId = bigint;
export type ReportStatus = { 'resolved' : null } |
  { 'submitted' : null } |
  { 'reviewed' : null };
export interface School { 'id' : SchoolId, 'name' : string, 'address' : string }
export type SchoolId = bigint;
export interface StaffAccount {
  'id' : StaffId,
  'principal' : Principal,
  'name' : string,
  'email' : string,
  'enabled' : boolean,
  'schoolId' : SchoolId,
}
export type StaffId = bigint;
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'schoolId' : [] | [SchoolId],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSchool' : ActorMethod<[string, string], SchoolId>,
  'createStaffAccount' : ActorMethod<
    [Principal, SchoolId, string, string],
    StaffId
  >,
  'deleteSchool' : ActorMethod<[SchoolId], undefined>,
  'deleteStaffAccount' : ActorMethod<[StaffId], undefined>,
  'getAdminDiagnostics' : ActorMethod<
    [],
    {
      'userRole' : string,
      'totalAdmins' : bigint,
      'hasAdminPermission' : boolean,
      'totalUsers' : bigint,
      'callerPrincipal' : string,
      'isAdmin' : boolean,
      'hasUserPermission' : boolean,
    }
  >,
  'getAllSchools' : ActorMethod<[], Array<School>>,
  'getAllSchoolsStats' : ActorMethod<
    [],
    Array<
      { 'totalReports' : bigint, 'schoolId' : SchoolId, 'schoolName' : string }
    >
  >,
  'getAllStaff' : ActorMethod<[], Array<StaffAccount>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyStaffAccount' : ActorMethod<[], [] | [StaffAccount]>,
  'getReportsBySchool' : ActorMethod<[SchoolId], Array<Report>>,
  'getReportsBySchoolAndCategory' : ActorMethod<
    [SchoolId, ReportCategory],
    Array<Report>
  >,
  'getReportsBySchoolAndDateRange' : ActorMethod<
    [SchoolId, Time, Time],
    Array<Report>
  >,
  'getSchool' : ActorMethod<[SchoolId], [] | [School]>,
  'getSchoolStats' : ActorMethod<
    [SchoolId],
    {
      'resolved' : bigint,
      'submitted' : bigint,
      'totalReports' : bigint,
      'reviewed' : bigint,
    }
  >,
  'getStaffBySchool' : ActorMethod<[SchoolId], Array<StaffAccount>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAnonymousReport' : ActorMethod<
    [SchoolId, ReportCategory, string],
    undefined
  >,
  'updateReportStatus' : ActorMethod<[ReportId, ReportStatus], undefined>,
  'updateSchool' : ActorMethod<[SchoolId, string, string], undefined>,
  'updateStaffAccount' : ActorMethod<
    [StaffId, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];