/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ReportId = bigint;
export type StaffId = bigint;
export type Time = bigint;
export type SchoolId = bigint;
export interface School {
    id: SchoolId;
    name: string;
    address: string;
}
export interface StaffAccount {
    id: StaffId;
    principal: Principal;
    name: string;
    email: string;
    enabled: boolean;
    schoolId: SchoolId;
}
export interface Report {
    id: ReportId;
    status: ReportStatus;
    text: string;
    schoolId: SchoolId;
    timestamp: Time;
    category: ReportCategory;
}
export interface UserProfile {
    name: string;
    role: string;
    schoolId?: SchoolId;
}
export enum ReportCategory {
    other = "other",
    suggestion = "suggestion",
    mentalHealth = "mentalHealth",
    bullying = "bullying",
    harassment = "harassment"
}
export enum ReportStatus {
    resolved = "resolved",
    submitted = "submitted",
    reviewed = "reviewed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createSchool(name: string, address: string): Promise<SchoolId>;
    createStaffAccount(principal: Principal, schoolId: SchoolId, name: string, email: string): Promise<StaffId>;
    deleteSchool(schoolId: SchoolId): Promise<void>;
    deleteStaffAccount(staffId: StaffId): Promise<void>;
    getAdminDiagnostics(): Promise<{
        userRole: string;
        totalAdmins: bigint;
        hasAdminPermission: boolean;
        totalUsers: bigint;
        callerPrincipal: string;
        isAdmin: boolean;
        hasUserPermission: boolean;
    }>;
    getAllSchools(): Promise<Array<School>>;
    getAllSchoolsStats(): Promise<Array<{
        totalReports: bigint;
        schoolId: SchoolId;
        schoolName: string;
    }>>;
    getAllStaff(): Promise<Array<StaffAccount>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyStaffAccount(): Promise<StaffAccount | null>;
    getReportsBySchool(schoolId: SchoolId): Promise<Array<Report>>;
    getReportsBySchoolAndCategory(schoolId: SchoolId, category: ReportCategory): Promise<Array<Report>>;
    getReportsBySchoolAndDateRange(schoolId: SchoolId, startTime: Time, endTime: Time): Promise<Array<Report>>;
    getSchool(id: SchoolId): Promise<School | null>;
    getSchoolStats(schoolId: SchoolId): Promise<{
        resolved: bigint;
        submitted: bigint;
        totalReports: bigint;
        reviewed: bigint;
    }>;
    getStaffBySchool(schoolId: SchoolId): Promise<Array<StaffAccount>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitAnonymousReport(schoolId: SchoolId, category: ReportCategory, text: string): Promise<void>;
    updateReportStatus(reportId: ReportId, status: ReportStatus): Promise<void>;
    updateSchool(schoolId: SchoolId, name: string, address: string): Promise<void>;
    updateStaffAccount(staffId: StaffId, name: string, email: string, enabled: boolean): Promise<void>;
}
import type { Report as _Report, ReportCategory as _ReportCategory, ReportId as _ReportId, ReportStatus as _ReportStatus, School as _School, SchoolId as _SchoolId, StaffAccount as _StaffAccount, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSchool(arg0: string, arg1: string): Promise<SchoolId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSchool(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSchool(arg0, arg1);
            return result;
        }
    }
    async createStaffAccount(arg0: Principal, arg1: SchoolId, arg2: string, arg3: string): Promise<StaffId> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaffAccount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaffAccount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteSchool(arg0: SchoolId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSchool(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSchool(arg0);
            return result;
        }
    }
    async deleteStaffAccount(arg0: StaffId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaffAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaffAccount(arg0);
            return result;
        }
    }
    async getAdminDiagnostics(): Promise<{
        userRole: string;
        totalAdmins: bigint;
        hasAdminPermission: boolean;
        totalUsers: bigint;
        callerPrincipal: string;
        isAdmin: boolean;
        hasUserPermission: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDiagnostics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDiagnostics();
            return result;
        }
    }
    async getAllSchools(): Promise<Array<School>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSchools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSchools();
            return result;
        }
    }
    async getAllSchoolsStats(): Promise<Array<{
        totalReports: bigint;
        schoolId: SchoolId;
        schoolName: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSchoolsStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSchoolsStats();
            return result;
        }
    }
    async getAllStaff(): Promise<Array<StaffAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStaffAccount(): Promise<StaffAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStaffAccount();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStaffAccount();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsBySchool(arg0: SchoolId): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsBySchool(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsBySchool(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsBySchoolAndCategory(arg0: SchoolId, arg1: ReportCategory): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsBySchoolAndCategory(arg0, to_candid_ReportCategory_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsBySchoolAndCategory(arg0, to_candid_ReportCategory_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsBySchoolAndDateRange(arg0: SchoolId, arg1: Time, arg2: Time): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsBySchoolAndDateRange(arg0, arg1, arg2);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsBySchoolAndDateRange(arg0, arg1, arg2);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchool(arg0: SchoolId): Promise<School | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchool(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchool(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchoolStats(arg0: SchoolId): Promise<{
        resolved: bigint;
        submitted: bigint;
        totalReports: bigint;
        reviewed: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchoolStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchoolStats(arg0);
            return result;
        }
    }
    async getStaffBySchool(arg0: SchoolId): Promise<Array<StaffAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffBySchool(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffBySchool(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitAnonymousReport(arg0: SchoolId, arg1: ReportCategory, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnonymousReport(arg0, to_candid_ReportCategory_n17(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnonymousReport(arg0, to_candid_ReportCategory_n17(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateReportStatus(arg0: ReportId, arg1: ReportStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSchool(arg0: SchoolId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSchool(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSchool(arg0, arg1, arg2);
            return result;
        }
    }
    async updateStaffAccount(arg0: StaffId, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffAccount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffAccount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_ReportCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportCategory): ReportCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_School]): School | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SchoolId]): SchoolId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffAccount]): StaffAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReportId;
    status: _ReportStatus;
    text: string;
    schoolId: _SchoolId;
    timestamp: _Time;
    category: _ReportCategory;
}): {
    id: ReportId;
    status: ReportStatus;
    text: string;
    schoolId: SchoolId;
    timestamp: Time;
    category: ReportCategory;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n13(_uploadFile, _downloadFile, value.status),
        text: value.text,
        schoolId: value.schoolId,
        timestamp: value.timestamp,
        category: from_candid_ReportCategory_n15(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    schoolId: [] | [_SchoolId];
}): {
    name: string;
    role: string;
    schoolId?: SchoolId;
} {
    return {
        name: value.name,
        role: value.role,
        schoolId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.schoolId))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    submitted: null;
} | {
    reviewed: null;
}): ReportStatus {
    return "resolved" in value ? ReportStatus.resolved : "submitted" in value ? ReportStatus.submitted : "reviewed" in value ? ReportStatus.reviewed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    suggestion: null;
} | {
    mentalHealth: null;
} | {
    bullying: null;
} | {
    harassment: null;
}): ReportCategory {
    return "other" in value ? ReportCategory.other : "suggestion" in value ? ReportCategory.suggestion : "mentalHealth" in value ? ReportCategory.mentalHealth : "bullying" in value ? ReportCategory.bullying : "harassment" in value ? ReportCategory.harassment : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n11(_uploadFile, _downloadFile, x));
}
function to_candid_ReportCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportCategory): _ReportCategory {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    schoolId?: SchoolId;
}): {
    name: string;
    role: string;
    schoolId: [] | [_SchoolId];
} {
    return {
        name: value.name,
        role: value.role,
        schoolId: value.schoolId ? candid_some(value.schoolId) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportCategory): {
    other: null;
} | {
    suggestion: null;
} | {
    mentalHealth: null;
} | {
    bullying: null;
} | {
    harassment: null;
} {
    return value == ReportCategory.other ? {
        other: null
    } : value == ReportCategory.suggestion ? {
        suggestion: null
    } : value == ReportCategory.mentalHealth ? {
        mentalHealth: null
    } : value == ReportCategory.bullying ? {
        bullying: null
    } : value == ReportCategory.harassment ? {
        harassment: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    resolved: null;
} | {
    submitted: null;
} | {
    reviewed: null;
} {
    return value == ReportStatus.resolved ? {
        resolved: null
    } : value == ReportStatus.submitted ? {
        submitted: null
    } : value == ReportStatus.reviewed ? {
        reviewed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
